Use poll instead of select
This patch ensures that there is no risk of reaching FD_SETSIZE
in a pipe FD. That would prevent select to run and would return
an error:

  ValueError: filedescriptor out of range in select()

This patch is complementary to

  https://github.com/canonical/craft-cli/pull/103

and both should be applied to fully fix the bug.