Fix unitary tests in local
When running "make test-units" from a shell, several tests fail
with the error:

  RuntimeError: Emitter needs to be initiated first

This patch fixes this by initializing the 'emit' object.

Fix https://github.com/canonical/craft-cli/issues/105